language: python
dist: bionic

install:
  - pip install --upgrade pot pytest keras tensorflow scikit-learn
  - pip install .

script: 
  - pytest -v energyflow

stages:
  - test
  - deploy

jobs:
  include:
    - python: 2.7
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - stage: deploy
      python: 3.8
      install: pip3 install --upgrade twine
      script: python3 setup.py sdist bdist_wheel
      after_success: |
        if [ ! -z $TRAVIS_TAG ]; then
          python3 -m twine upload --skip-existing dist/*
        fi

branches:
  only:
    - master